version: '3.8'
services:
  app:
    build:
      context: ./js
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      OTEL_SERVICE_NAME: app-service
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
    depends_on:
      - fastapi
      - jaeger

  chained-app:
    build:
      context: ./js
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      OTEL_SERVICE_NAME: chained-app-service
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
    depends_on:
      - fastapi
      - jaeger

  fastapi:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      OTEL_SERVICE_NAME: python-fastapi-service
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # Jaeger UI
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
